### ISSUE TITLE
Application gets crashes on launch react native 0.61.0

### ISSUE THREAD

**Issue by gkolusu-assurant** [newrelic-experimental/NewRelicReactNativeModule#17]
Performed all setups as per document. Application crashes on launch.

React Native Version: 0.61.0
Platform: Android

Adb logcat

```
FATAL EXCEPTION: OkHttp Dispatcher
01-11 21:38:34.044  1358  1430 E AndroidRuntime: Process: com.new_relic.integration, PID: 1358
01-11 21:38:34.044  1358  1430 E AndroidRuntime: java.lang.ClassCastException: com.newrelic.agent.android.instrumentation.okhttp3.CallExtension cannot be cast to okhttp3.RealCall
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at okhttp3.OkHttpClient$1.streamAllocation(OkHttpClient.java:188)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at com.newrelic.agent.android.instrumentation.okhttp3.CallbackExtension.onResponse(CallbackExtension.java:42)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-11 21:38:34.044  1358  1430 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

Note: Sentry is integrated in the application as well

**Comment by MichaelOsowski** [comment]
What version of the New Relic Android Agent was used?  If you are using New Relic Agent version of 6.3.1 there is a reported issue with Okhttp3.  Use the 6.1.0 version of the SDK.  That should resolve the issue.
